"""Phien ban Skool Downloader (Phase ship)."""
__version__ = "3.3.0"
__codename__ = "course-os-complete"

# Phase milestones (gan dung commit history)
HISTORY = (
    "1.0 dashboard/queue/rag",
    "1.2 parallel+gdrive+tfidf",
    "1.3 onedrive+search",
    "1.4 web+health",
    "1.5 static site+embed+tray",
    "1.6 smart BASE+doctor",
    "1.7 download reliability",
    "1.8 fail UX+cleanup",
    "1.9 version+selftest+dash fails",
    "1.9.1 health fails count + dash fail button",
    "2.0.0 UI v2 — sidebar, stat cards, accent theme",
    "2.1.0 dark mode + queue/chat/manager polish",
    "2.2.0 wizard dump + env check + remaining screens",
    "2.3.0 density compact/comfortable + doctor polish",
    "2.4.0 fail-driven retry + knowledge pack + auto-index",
    "2.5.0 smart update + search highlight + pack backup/restore",
    "2.6.0 parallel workers + notify + resume/BM + digests",
    "2.7.0 adaptive workers + ETA + smart-batch + anki + quiz",
    "2.8.0 live ETA + learn playlist + content diff + vault + fix",
    "2.9.0 notes + disk report + study ICS + dash download strip",
    "2.10.0 notes search + sync badge + favorites + shortcuts + alias",
    "2.11.0 LLM custom prompt translate/update (Claude + OpenAI-compat)",
    "2.12.0 multi-LLM: Gemini/OpenRouter/GLM/Qwen/Kimi/… + fallback chain",
    "2.13.0 Grok (xAI) provider + features/workflows user guide",
    "2.14.0 one-click launchers + Desktop shortcuts (macOS/Win/Linux)",
    "2.14.1 rename display name to Skool Downloader",
    "2.14.2 fix macOS GUI hang (CLT Tk) + full SkoolDownloader rename",
    "2.15.0 pick output folder + live download progress (course/folder/video/lesson)",
    "2.15.1 video stats on UI (size/host/status) + usage guide update",
    "2.15.2 Finder/.app PATH fix for node+ffmpeg + Downloads shortcut refresh",
    "2.15.3 robust Skool browser recover + better chapter list (no blank lessons)",
    "2.15.4 browser via storage_state (fix closed-page on list chapters)",
    "2.15.5 classroom UX: keep Chrome open, live URL, auto-list chapters",
    "2.15.6 show all lessons (not only with URL) + better video extract",
    "2.16.0 full lesson pack: description/links/resources/lesson.json per folder",
    "2.16.1 chapters sorted 1,2,3 from _chapters.json / folder numbers",
    "2.17.0 Discovery scrape: all pages/languages/topics → SQLite+CSV table",
    "2.17.1 fix catalog Notes/Cost merge (paid≠Free) + repair-notes + member refresh resume",
    "2.17.2 free courses Cost = $0 (not '$0 (Free)') for revenue totals",
    "2.18.0 AUTO_TRANSCRIBE default + all transcript.txt (ordered plain text)",
    "2.18.1 Whisper auto-detect lang + lesson intro; toggle off; FEATURES+README",
    "2.19.0 per-lesson VI summary (purpose/summary/todo/quotes/resources)",
    "2.20.0 Dashboard URL Quick Run + toggles summary/thumbs + DeepSeek/Gemini LLM",
    "2.21.0 Course upgrade: market research DOCX → new structure (drop obsolete)",
    "2.21.1 Upgrade questionnaire (on by default) before research/structure",
    "2.22.0 Course Studio: asset packs + master EN/VI + locale hub",
    "2.22.1 Dashboard LLM panel: API keys + per-task model routing",
    "2.23.0 Course OS: wizard, video lab, publish, QA, glossary/TM, diff",
    "2.24.0 Video run-queue (ElevenLabs/HeyGen/Synthesia/local) · locale review · schedule · board · docs crawl · selective localize",
    "2.25.0 Pipeline status · slides HTML · ops CLI (glossary/budget) · relocalize rejected · media keys GUI · budget gate · Win schedule",
    "2.26.0 PPTX · thumbs · side-by-side review · incremental re-upgrade · cost dashboard · golden eval · Skool clipboard · sales HTML · YT helper",
    "2.27.0 Portfolio · board HTML · student portal · A/B titles · voice preview · approve→render · locale glossary · RTL slides",
    "2.28.0 Board DnD reorder · competitor scan · Notion export + webhook · wizard auto-status/notify",
    "3.0.0 Course OS COMPLETE — finish-all · feature registry · expanded status/ship · tests_course_os",
    "3.1.0 Offline finish: structure_from_dump + bootstrap assets (no LLM) · GUI offline mode",
    "3.1.1 Fix publish_zip self-include runaway · offline localize skip marker · safe zip limits",
    "3.2.0 OmniVoice TTS (local MPS) · per-lesson on/off · Streamlit UI · video provider omnivoice",
    "3.2.1 OmniVoice playlist HTML · portal audio players · TTS toggle board import",
    "3.2.2 OmniVoice TTS default OFF (opt-in per lesson / enable-all)",
    "3.3.0 OpenRouter task routing: DeepSeek V4 Flash→MiMo-V2.5 · rankings refresh · cost estimate UI",
)


def version_string():
    return f"Skool Downloader {__version__} ({__codename__})"
